<?php
/**
 * Created By : RH
 */
?>
<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="rh_products" data-form-part="edit_movie_form" id="rh_products" value=""  />
<script type="text/x-magento-init">
    {
        "*": {
            "Magenest_Movie/js/assign-products": {
                "selectedProducts":  <?= /* @escapeNotVerified */ $block->getProductsJson() ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>
