<?php
/**
 *
  * Copyright © 2018 Magenest. All rights reserved.
  * See COPYING.txt for license details.
  *
  * Magenest_InstagramShop extension
  * NOTICE OF LICENSE
  *
  * @category Magenest
  * @package  Magenest_InstagramShop
  * @author    dangnh@magenest.com

 */

namespace Magenest\InstagramShop\Model\ResourceModel\Photo;

use Magenest\InstagramShop\Model\Photo;

/**
 * Class Collection
 * @package Magenest\InstagramShop\Model\ResourceModel\Photo
 */
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'id';

    /**
     * Initialize resource collection
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init('Magenest\InstagramShop\Model\Photo', 'Magenest\InstagramShop\Model\ResourceModel\Photo');
    }

    /**
     * @return Photo[]
     */
    public function getPhotoIdItems()
    {
        $result = [];
        $items  = $this->getItems();
        foreach ($items as $item) {
            if (!isset($result[$item->getPhotoId()])) {
                $result[$item->getPhotoId()] = $item;
            }
        }
        return $result;
    }

    /**
     * @param $ids
     * @return $this
     */
    public function addIdsFilter($ids)
    {
        $this->addFieldToFilter($this->getIdFieldName(), ['in' => $ids]);
        return $this;
    }

    /**
     * @return Photo[]
     */
    public function getItems()
    {
        return parent::getItems(); // TODO: Change the autogenerated stub
    }
}
