<?php
/**
 *
  * Copyright © 2018 Magenest. All rights reserved.
  * See COPYING.txt for license details.
  *
  * Magenest_InstagramShop extension
  * NOTICE OF LICENSE
  *
  * @category Magenest
  * @package  Magenest_InstagramShop
  * @author    dangnh@magenest.com

 */

/** @var $block \Magenest\InstagramShop\Block\Photo\Renderer */
if ($sliderBlock = $block->getSliderBlock()) {

    $photos        = $sliderBlock->getPhotos();
    $slickConfig   = $sliderBlock->getData();
    $totalItems    = $photos->getSize();
    $itemsPerSlide = $sliderBlock->getItemsPerSlide();

    $prefixElementClass = uniqid();
    ?>
    <div id="slider-<?=$prefixElementClass?>">
        <div class="slider">
            <?= $block->getSharedPopupHtml() ?>
        </div>
        <div class="block block-photo-slider slider-list container">
            <div class="block-title">
                <h2 class="title"><?php echo $sliderBlock->getTitle() ?></h2>
            </div>
            <div class="block-content">
                <?php if ($totalItems) { ?>
                    <div class="flexslider carousel">
                        <ul class="slides <?=$prefixElementClass?>">
                            <?php
                            $count = 0;
                            /** @var \Magenest\InstagramShop\Model\Photo $photo */
                            foreach ($photos as $photo) { ?>
                                <?php
                                if (!$sliderBlock->isDefaultTemplate() && $count % $itemsPerSlide == 0) {
                                    echo('<li class="slide-item"><ul class="' . $block->getItemsPerSlideClass() . '-photo">');
                                } ?>
                                <li id="<?= $photo->getPhotoId() ?>">
                                    <?php if (!$sliderBlock->isDefaultTemplate()){?>
                                        <a class="instagram-link-photo" href="<?= $photo->getUrl() ?>" style="background-image: url(<?= $photo->getSource() ?>);">
                                            <div class="overlay"></div>
                                            <div class="text">
                                                <img src="<?= $this->getViewFileUrl('Magenest_InstagramShop::images/instagram.png') ?>" alt=""/>
                                                <button><?= $sliderBlock->getHoverText() ?></button>
                                            </div>
                                        </a>
                                    <?php } else{ ?>
                                        <a href="<?= $photo->getUrl() ?>">
                                            <img src="<?= $photo->getSource() ?>" alt=""/>
                                            <div class="overlay"></div>
                                            <div class="text">
                                                <img src="<?= $this->getViewFileUrl('Magenest_InstagramShop::images/instagram.png') ?>" alt=""/>
                                                <button><?= $sliderBlock->getHoverText() ?></button>
                                            </div>
                                        </a>
                                    <?php }?>
                                    <?=  $sliderBlock->getLinkedProductsHtml($photo) ?>
                                    <?= $sliderBlock->getHotspotHtml($photo) ?>
                                    <?php if ($sliderBlock->canShowVideo()) {
                                        echo $sliderBlock->getVideoHtml($photo);
                                    } ?>
                                </li>
                                <?php
                                $count++;
                                if (!$sliderBlock->isDefaultTemplate() && ($count % $itemsPerSlide == 0 || $count == $totalItems)) {
                                    echo('</ul></li>');
                                } ?>
                            <?php } ?>
                        </ul>
                    </div>
                    <div class="gallery-btn-block">
                        <a href="<?= $sliderBlock->getUrl('instagram/gallery/') ?>" class="instagram-button"
                           style="<?= $sliderBlock->getViewFullGalleryCss() ?>">
                            <?= $sliderBlock->getViewFullGalleryTitle() ?>
                        </a>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <?php if ($photos->getSize()) : ?>
        <script>
            require(['jquery'], function ($) {
                $(function () {
                    require(['flexslider'], function () {
                        $('#slider-<?=$prefixElementClass?> .flexslider').flexslider({
                            animation: "slide",
                            easing: "swing",
                            direction: "<?=$sliderBlock->getConfigSliderValue($sliderBlock->getDirection(), 'horizontal', true)?>",
                            reverse: <?=$sliderBlock->getConfigSlider($sliderBlock->getReverse(), 'false')?>,
                            animationLoop: <?=$sliderBlock->getConfigSlider($sliderBlock->getAnimationLoop())?>,
                            smoothHeight: <?=$sliderBlock->getConfigSlider($sliderBlock->getSmoothHeight(), 'false')?>,
                            startAt: <?=$sliderBlock->getConfigSliderValue($sliderBlock->getStartAt(), 0)?>,
                            slideshow: <?=$sliderBlock->getConfigSlider($sliderBlock->getSlideshow())?>,
                            slideshowSpeed: <?=$sliderBlock->getConfigSliderValue($sliderBlock->getSlideShowSpeed(), 7000)?>,
                            animationSpeed: <?=$sliderBlock->getConfigSliderValue($sliderBlock->getAnimationSpeed(), 600)?>,
                            initDelay: <?=$sliderBlock->getConfigSliderValue($sliderBlock->getInitDelay(), 0)?>,
                            randomize: <?=$sliderBlock->getConfigSlider($sliderBlock->getRandomize(), 'false')?>,
                            pauseOnAction: <?=$sliderBlock->getConfigSlider($sliderBlock->getPauseOnAction())?>,
                            pauseOnHover: <?=$sliderBlock->getConfigSlider($sliderBlock->getPauseOnHover(), 'false')?>,
                            useCSS: <?=$sliderBlock->getConfigSlider($sliderBlock->getUseCSS())?>,
                            touch: <?=$sliderBlock->getConfigSlider($sliderBlock->getTouch())?>,
                            video: <?=$sliderBlock->getConfigSlider($sliderBlock->getVideo(), 'false')?>,
                            controlNav: <?=$sliderBlock->getConfigSlider($sliderBlock->getControlNav())?>,
                            directionNav: <?=$sliderBlock->getConfigSlider($sliderBlock->getDirectionNav())?>,
                            keyboard: <?=$sliderBlock->getConfigSlider($sliderBlock->getKeyboard())?>,
                            multipleKeyboard: <?=$sliderBlock->getConfigSlider($sliderBlock->getMultipleKeyboard(), 'false')?>,
                            mousewheel: <?=$sliderBlock->getConfigSlider($sliderBlock->getMousewheel(), 'false')?>,
                            pausePlay: <?=$sliderBlock->getConfigSlider($sliderBlock->getPausePlay(), 'false')?>,
                            pauseText: "<?=$sliderBlock->getConfigSliderValue($sliderBlock->getPauseText(), 'Pause', true)?>",
                            playText: "<?=$sliderBlock->getConfigSliderValue($sliderBlock->getPlayText(), 'Play', true)?>",
                            itemWidth: <?=$sliderBlock->getConfigSliderValue($sliderBlock->getItemWidth(),0)?>,
                            itemMargin: <?=$sliderBlock->getConfigSliderValue($sliderBlock->getItemMargin(), 0)?>,
                            minItems: <?=$sliderBlock->getConfigSliderValue($sliderBlock->getMinItems(), 0)?>,
                            maxItems: <?=$sliderBlock->getConfigSliderValue($sliderBlock->getMaxItems(), 0)?>,
                            move: <?=$sliderBlock->getConfigSliderValue($sliderBlock->getMove(), 0)?>,
                            rtl: <?=$sliderBlock->getConfigSlider($sliderBlock->getRtl(), 'false')?>
                        });
                    });

                });
            });
            require(['mage/url'], function (urlBuilder) {
                return urlBuilder.setBaseUrl('<?=$sliderBlock->getBaseUrl()?>');
            });
        </script>
        <script type="text/x-magento-init">
        {
            "#slider-<?=$prefixElementClass?>": {
                "instagramPopup": {
                    "photos" : <?= json_encode($photos->getData()) ?>,
                    "canShowVideo": <?= $sliderBlock->canShowVideo() ? 'true' : 'false' ?>,
                    "prefixContainer":".slider",
                    "prefixElement":".flex-viewport ul.<?=$prefixElementClass?> li"
                }
            }
        }

        </script>
    <?php endif; ?>
<?php } ?>
