<?php
/**
 *
 * Copyright © 2018 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Magenest_InstagramShop extension
 * NOTICE OF LICENSE
 *
 * @category Magenest
 * @package  Magenest_InstagramShop
 * @author    dangnh@magenest.com
 */

namespace Magenest\InstagramShop\Block\Adminhtml\System\Config\Form;

use Magento\Framework\App\ObjectManager;
use Magento\Theme\Model\Theme;

/**
 * Class CreateWidget
 * @package Magenest\InstagramShop\Block\Adminhtml\System\Config\Form
 */
class CreateWidget extends \Magento\Config\Block\System\Config\Form\Field
{

    /**
     * @var \Magento\Framework\Data\Form\Element\AbstractElement
     */
    protected $element;

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->setTemplate('Magenest_InstagramShop::system/config/create-template.phtml');

    }

    /**
     * @return \Magento\Framework\Data\Form\Element\AbstractElement
     */
    public function getElement()
    {
        return $this->element;
    }

    /**
     * @param \Magento\Framework\Data\Form\Element\AbstractElement $element
     * @return string
     */
    public function render(\Magento\Framework\Data\Form\Element\AbstractElement $element)
    {
        $this->element = $element;
        return $this->toHtml();
    }

    /**
     * @return string
     */
    public function getCreateWidgetUrl()
    {
        return $this->_urlBuilder->getUrl('instagram/instagram/createWidget');
    }

    /**
     * @return Theme[]
     */
    public function getThemes()
    {
        $items = ObjectManager::getInstance()->create(Theme::class)->getCollection()->addAreaFilter()->setOrder('theme_id', 'DESC')->getItems();
        return $items;
    }
}