<?php
/**
 *
  * Copyright © 2018 Magenest. All rights reserved.
  * See COPYING.txt for license details.
  *
  * Magenest_InstagramShop extension
  * NOTICE OF LICENSE
  *
  * @category Magenest
  * @package  Magenest_InstagramShop
  * @author    dangnh@magenest.com

 */

namespace Magenest\InstagramShop\Block\Adminhtml\System\Config\Form;
/**
 * Class GalleryTemplate
 * @package Magenest\InstagramShop\Block\Adminhtml\System\Config\Form
 */
class GalleryTemplate extends \Magento\Config\Block\System\Config\Form\Field
{
    /**
     * @var \Magento\Framework\Data\Form\Element\AbstractElement
     */
    protected $element;

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->setTemplate('Magenest_InstagramShop::system/config/gallery-template.phtml');

    }

    /**
     * @return \Magento\Framework\Data\Form\Element\AbstractElement
     */
    public function getElement()
    {
        return $this->element;
    }

    /**
     * @param \Magento\Framework\Data\Form\Element\AbstractElement $element
     * @return string
     */
    public function render(\Magento\Framework\Data\Form\Element\AbstractElement $element)
    {
        $this->element = $element;
        return $this->toHtml();
    }

    /**
     * @param string $value
     * @return string
     */
    public function getChecked($value)
    {
        return $this->getElement()->getValue() == $value ? 'checked="checked"' : '';
    }
}