<?php
/**
 *
 * Copyright © 2018 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Magenest_InstagramShop extension
 * NOTICE OF LICENSE
 *
 * @category Magenest
 * @package  Magenest_InstagramShop
 * @author    dangnh@magenest.com
 */

/** @var $block Magenest\InstagramShop\Block\Gallery\Gallery */
/** get tags from store configuration */
$tags = $block->getTags();
/** get view param */
$view = $block->getViewParam();
/** get page param */
$page         = $block->getPageParam();
$canShowVideo = $block->canShowVideo();
$photos       = $block->getCollection();
$helper       = $this->helper(\Magenest\InstagramShop\Helper\Helper::class);
?>
<div id="instagram-gallery">
    <div class="gallery">
        <?= $block->getChildHtml('shared-popup') ?>
    </div>
    <!-- gallery view navigation, includes gallery & tags   -->
    <div class="gallery-nav">
        <!-- gallery button   -->
        <a href="<?= $helper->getBaseGalleryUrl() ?>">
            <div class="gallery-url <?php if (empty($view)) echo 'chosen' ?>"><?= __('Gallery') ?></div>
        </a>
        <?php

        if (!empty($tags)) {
            foreach ($tags as $tag) {
                if (!empty($tag)) {
                    ?>
                    <!-- tags button  -->
                    <a href="<?= $helper->getBaseGalleryUrl() . '/' . $tag ?>">
                        <div class='gallery-url <?php if (!empty($view) && $tag == $view) echo 'chosen' ?>'>
                            <?php echo "#" . $tag ?>
                        </div>
                    </a>
                    <?php
                }
            }
        }
        ?>
    </div>
    <?php if ($photos->getSize() == 0) { ?>
        <h2><?= __('There are no photo to display yet, please comeback later.') ?></h2>
    <?php } else { ?>

        <div class="widget-normal-timeline widget-desktop widget-wrapper widget-lookbook <?= $block->isDefaultGalleryTemplate() ?: 'gallery-grid' ?>">
            <?php
            /** @var \Magenest\InstagramShop\Model\Photo $photo */
            foreach ($photos as $photo) { ?>
                <div id="widget-timeline-<?= $photo->getPhotoId() ?>" class="widget-timeline">
                    <div class="widget-entry-container">
                        <div id="<?= $photo->getPhotoId() ?>" class="widget-timeline-entry"
                             style="cursor: pointer; background-image: url('<?= $photo->getSource() ?>');">
                            <div class="widget-text-container">
                                <div class="widget-service-icon"><i class="widget-icon widget-fa-instagram"></i></div>
                                <div class="widget-timeline-text">
                                    <div class="widget-entry-title"><?= $block->escapeHtml($photo->getCaption()) ?></div>
                                </div>
                            </div>
                            <?= $block->getLinkedProductsHtml($photo) ?>
                            <?= $block->getHotspotHtml($photo) ?>
                            <?php
                            if ($canShowVideo) {
                                echo $block->getVideoHtml($photo);
                            } ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <div style="clear: both"></div>
            <div class="toolbar-bottom">
                <div class="toolbar">
                    <?php echo $block->getPagerHtml(); ?>
                </div>
            </div>
        </div>
        <script type="text/x-magento-init">
        {
            "#instagram-gallery": {
                "instagramPopup": {
                    "photos" : <?= json_encode($photos->getData()) ?>,
                    "prefixContainer":".gallery",
                    "prefixElement":".widget-normal-timeline div.widget-timeline-entry",
                    "optionGalleryPage": ".widget-text-container",
                    "canShowVideo": <?= $canShowVideo ? 'true' : 'false' ?>
                }
            }
        }


        </script>
    <?php } ?>
</div>