<?php
/**
 *
 * Copyright © 2018 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Magenest_InstagramShop extension
 * NOTICE OF LICENSE
 *
 * @category Magenest
 * @package  Magenest_InstagramShop
 * @author    dangnh@magenest.com
 */

namespace Magenest\InstagramShop\Model\ResourceModel;

/**
 * Class Photo
 * @package Magenest\InstagramShop\Model\ResourceModel
 */
class Photo extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * DB connection
     *
     * @var \Magento\Framework\DB\Adapter\AdapterInterface
     */
    protected $connection;

    protected function _construct()
    {
        $this->_init('magenest_instagram_photo', 'id');
        $this->connection = $this->getConnection();
    }

    /**
     * @param \Magenest\InstagramShop\Model\Photo $photo
     * @param $photoId
     * @return $this
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function loadByPhotoId(\Magenest\InstagramShop\Model\Photo $photo, $photoId)
    {
        $select = $this->connection->select()->from($this->getMainTable())->where('photo_id=:photo_id');
        $id     = $this->connection->fetchOne($select, ['photo_id' => $photoId]);
        if ($id) {
            $this->load($photo, $id);
        } else {
            $photo->setData([]);
        }
        return $this;
    }

    /**
     * @param \Magento\Framework\Model\AbstractModel $object
     * @return \Magento\Framework\Model\ResourceModel\Db\AbstractDb
     */
    protected function _beforeDelete(\Magento\Framework\Model\AbstractModel $object)
    {
        $this->_deleteHotspots($object);
        $this->_deleteReports($object);
        return parent::_beforeDelete($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Magento\Framework\DataObject $object
     */
    private function _deleteHotspots(\Magento\Framework\DataObject $object)
    {
        $hotspotTable = $this->connection->getTableName('magenest_instagramshop_hotspot');
        $select       = $this->connection->select()->from($hotspotTable, ['hotspot_id'])->where('photo_id = ?', $object->getPhotoId());
        $ids          = $this->connection->fetchCol($select);
        if (count($ids)){
            $ids          = "('" . implode("','", $ids) . "')";
            $this->connection->delete($hotspotTable, 'hotspot_id IN ' . $ids);
        }
    }

    /**
     * @param \Magento\Framework\DataObject $object
     */
    private function _deleteReports(\Magento\Framework\DataObject $object)
    {
        $reportTable = $this->connection->getTableName('magenest_instagramshop_report');
        $select       = $this->connection->select()->from($reportTable, ['id'])->where('photo_id = ?', $object->getPhotoId());
        $ids          = $this->connection->fetchCol($select);
        if (count($ids)){
            $ids          = "('" . implode("','", $ids) . "')";
            $this->connection->delete($reportTable, 'id IN ' . $ids);
        }
    }
}
