<fieldset class="fieldset create account">
    <legend class="legend"><span><?php /* @escapeNotVerified */echo __('Additional Information') ?></span></legend><br>
    <div class="field is_manager">
        <input type="checkbox" name="is_manager" title="I'm a cyber manager" value="1" id="is_manager" class="checkbox">
        <label for="is_manager" class="label"><span>I'm a cyber manager</span></label>
    </div>
</fieldset>