<?php
/**
 *
 * Copyright © 2018 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * Magenest_InstagramShop extension
 * NOTICE OF LICENSE
 *
 * @category Magenest
 * @package  Magenest_InstagramShop
 * @author    dangnh@magenest.com
 */

/** @var $block \Magenest\InstagramShop\Block\Adminhtml\System\Config\Form\GalleryTemplate */
$elementId            = $block->getElement()->getId();
$defaultTemplateValue = \Magenest\InstagramShop\Model\Config\Source\GalleryTemplate::DEFAULT_VALUE_TEMPLATE;
$mixTemplateValue     = \Magenest\InstagramShop\Model\Config\Source\GalleryTemplate::MIX_VALUE_TEMPLATE;
?>
<tr id="row_<?= $elementId ?>">
    <td class="label">
        <label for="<?= $elementId ?>">
            <span data-config-scope="<?= $block->getElement()->getScopeLabel() ?>"><?= $block->getElement()->getLabel() ?></span>
        </label>
    </td>
    <td class="value">
        <div class="admin__field admin__field-option" style="display: inline;">
            <input type="radio"
                   name="<?= $block->getElement()->getName() ?>"
                   value="<?= $defaultTemplateValue ?>"
                   class="admin__control-radio"
                   id="<?= $elementId . $defaultTemplateValue ?>"
                <?= $block->getChecked($defaultTemplateValue) ?>>
            <label class="admin__field-label" for="<?= $elementId . $defaultTemplateValue ?>">
                <img class="zoomable"
                     src="<?= $block->getViewFileUrl('Magenest_InstagramShop::images/default-grid.png') ?>"
                     alt="Default Grid Template"/>
            </label>
        </div>
        <div class="admin__field admin__field-option" style="display: inline;">
            <input type="radio"
                   name="<?= $block->getElement()->getName() ?>"
                   value="<?= $mixTemplateValue ?>" class="admin__control-radio"
                   id="<?= $elementId . $mixTemplateValue ?>"
                <?= $block->getChecked($mixTemplateValue) ?>>
            <label class="admin__field-label" for="<?= $elementId . $mixTemplateValue ?>">
                <img class="zoomable" src="<?= $block->getViewFileUrl('Magenest_InstagramShop::images/mix-grid.png') ?>"
                     alt="Mix Grid Template"/>
            </label>
        </div>
    </td>
</tr>