<h2>Detail</h2>

<div class="admin__page-section-item-content">
    <table class="admin__table-secondary order-information-table">
        <tbody>
        <tr>
            <th>Numbers of Customers :</th>
            <td><?php echo $block->getNumberCustomer(); ?></td>
        </tr>

        <tr>
            <th>Numbers of Products : </th>
            <td><?php echo $block->getNumberProduct(); ?></td>
        </tr>

        <tr>
            <th>Numbers of Orders :</th>
            <td><?php echo $block->getNumberOrder(); ?></td>
        </tr>

        <tr>
            <th>Numbers of Invoices :</th>
            <td><?php echo $block->getNumberInvoice(); ?></td>
        </tr>

        <tr>
            <th>Numbers of Creditmemos :</th>
            <td><?php echo $block->getNumberCreditmemo(); ?></td>
        </tr>
        </tbody>
    </table>
</div>